api_configuration:
    path: /api/configuration
    methods: [GET|POST]
    defaults:
        _controller: Synolia\SyliusAkeneoPlugin\Controller\ApiConfigurationController

akeneo_admin_product_filters_rules_create:
    path: /product-filters-rules/new
    methods: [GET|POST]
    defaults:
        _controller: Synolia\SyliusAkeneoPlugin\Controller\ProductFilterRulesController::createAction

akeneo_admin_product_filters_rules_update:
    path: /product-filters-rules/{id}/edit
    methods: [GET|POST]
    defaults:
        _controller: Synolia\SyliusAkeneoPlugin\Controller\ProductFilterRulesController::updateAction

categories:
    path: /categories
    methods: [GET|POST]
    defaults:
        _controller: Synolia\SyliusAkeneoPlugin\Controller\CategoriesController

products:
    path: /Products
    methods: [GET|POST]
    defaults:
        _controller: Synolia\SyliusAkeneoPlugin\Controller\ProductsController

attributes:
    path: /attributes
    methods: [GET|POST]
    defaults:
        _controller: Synolia\SyliusAkeneoPlugin\Controller\AttributesController

medias:
    path: /medias
    methods: [GET|POST]
    defaults:
        _controller: Synolia\SyliusAkeneoPlugin\Controller\MediasController
